terminal_source: usb
software_timer:
  priority: 2
  stack_depth: 1024
SPI:
  spi4:
    tx_buffer_size: 51200
    rx_buffer_size: 51200
    dma_section: .axi_ram
    dma_enable_min_size: 3
  spi1:
    tx_buffer_size: 1024
    rx_buffer_size: 1024
    dma_section: .axi_ram
    dma_enable_min_size: 3
I2C:
  i2c1:
    buffer_size: 32
    dma_section: .axi_ram
    dma_enable_min_size: 3
USB:
  tx_queue_size: 5
Terminal:
  read_buff_size: 32
  max_line_size: 32
  max_arg_number: 5
  max_history_number: 5
  run_as_thread: true
  thread_stack_depth: 1024
  thread_priority: 3
SYSTEM: FreeRTOS
FlashLayout:
  model: STM32H750VBT6
  flash_base: '0x08000000'
  flash_size_kb: 128
  sectors:
  - index: 0
    address: '0x08000000'
    size_kb: 128.0
device_aliases:
  power_manager:
    type: PowerManager
    aliases:
    - power_manager
  PC13:
    type: GPIO
    aliases:
    - PC13
    - user_key
  SPI1_CS:
    type: GPIO
    aliases:
    - SPI1_CS
  LCD_CS:
    type: GPIO
    aliases:
    - LCD_CS
    - st7735_spi_cs
  LCD_WR_RS:
    type: GPIO
    aliases:
    - LCD_WR_RS
    - st7735_spi_rs
  LED:
    type: GPIO
    aliases:
    - LED
  pwm_tim1_ch2n:
    type: PWM
    aliases:
    - pwm_tim1_ch2n
    - st7735_pwm
  spi1:
    type: SPI
    aliases:
    - spi1
  spi4:
    type: SPI
    aliases:
    - spi4
    - st7735_spi
  i2c1:
    type: I2C
    aliases:
    - i2c1
  uart_cdc:
    type: UART
    aliases:
    - uart_cdc
  ramfs:
    type: RamFS
    aliases:
    - ramfs
  terminal:
    type: Terminal<32, 32, 5, 5>
    aliases:
    - terminal
